-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DMA24bUnit_mm2s is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 128;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    STR_video_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    STR_video_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    STR_video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    STR_video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    image_w : IN STD_LOGIC_VECTOR (11 downto 0);
    image_h : IN STD_LOGIC_VECTOR (11 downto 0);
    image_in : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_start : IN STD_LOGIC;
    STR_video_out_TVALID : OUT STD_LOGIC;
    STR_video_out_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of DMA24bUnit_mm2s is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "DMA24bUnit_mm2s_DMA24bUnit_mm2s,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.660000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.861800,HLS_SYN_LAT=307211,HLS_SYN_TPT=307204,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=1141,HLS_SYN_LUT=1525,HLS_VERSION=2020_2}";
    constant C_M_AXI_ID_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 40;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_M_AXI_AWUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ARUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_WUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_RUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_BUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal gmem_RLAST : STD_LOGIC;
    signal gmem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_n_inv : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_start : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_done : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_continue : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_idle : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_ap_ready : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_start_out : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_start_write : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWVALID : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_WVALID : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_WLAST : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARVALID : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_RREADY : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_m_axi_gmem_BREADY : STD_LOGIC;
    signal DMA24b_mm2s_fetch_U0_mm_fifo3_din : STD_LOGIC_VECTOR (127 downto 0);
    signal DMA24b_mm2s_fetch_U0_mm_fifo3_write : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_start : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_done : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_continue : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_idle : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_ap_ready : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_mm_fifo3_read : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TVALID : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal DMA24b_mm2s_streamout_U0_STR_video_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal mm_fifo_full_n : STD_LOGIC;
    signal mm_fifo_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal mm_fifo_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_DMA24b_mm2s_streamout_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_DMA24b_mm2s_streamout_U0_full_n : STD_LOGIC;
    signal start_for_DMA24b_mm2s_streamout_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_DMA24b_mm2s_streamout_U0_empty_n : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_start_full_n : STD_LOGIC;
    signal DMA24b_mm2s_streamout_U0_start_write : STD_LOGIC;

    component DMA24bUnit_mm2s_DMA24b_mm2s_fetch IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mm_fifo3_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        mm_fifo3_full_n : IN STD_LOGIC;
        mm_fifo3_write : OUT STD_LOGIC;
        mm_buffer : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component DMA24bUnit_mm2s_DMA24b_mm2s_streamout IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mm_fifo3_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        mm_fifo3_empty_n : IN STD_LOGIC;
        mm_fifo3_read : OUT STD_LOGIC;
        STR_video_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        STR_video_out_TVALID : OUT STD_LOGIC;
        STR_video_out_TREADY : IN STD_LOGIC;
        STR_video_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        STR_video_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        STR_video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        STR_video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component DMA24bUnit_mm2s_fifo_w128_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component DMA24bUnit_mm2s_start_for_DMA24b_mm2s_streamout_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component DMA24bUnit_mm2s_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    gmem_m_axi_U : component DMA24bUnit_mm2s_gmem_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 128,
        USER_AW => 64,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 64,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARVALID,
        I_ARREADY => gmem_ARREADY,
        I_ARADDR => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARADDR,
        I_ARID => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARID,
        I_ARLEN => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLEN,
        I_ARSIZE => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARSIZE,
        I_ARLOCK => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLOCK,
        I_ARCACHE => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARCACHE,
        I_ARQOS => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARQOS,
        I_ARPROT => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARPROT,
        I_ARUSER => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARUSER,
        I_ARBURST => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARBURST,
        I_ARREGION => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARREGION,
        I_RVALID => gmem_RVALID,
        I_RREADY => DMA24b_mm2s_fetch_U0_m_axi_gmem_RREADY,
        I_RDATA => gmem_RDATA,
        I_RID => gmem_RID,
        I_RUSER => gmem_RUSER,
        I_RRESP => gmem_RRESP,
        I_RLAST => gmem_RLAST,
        I_AWVALID => ap_const_logic_0,
        I_AWREADY => gmem_AWREADY,
        I_AWADDR => ap_const_lv64_0,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_0,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => ap_const_logic_0,
        I_WREADY => gmem_WREADY,
        I_WDATA => ap_const_lv128_lc_1,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv16_0,
        I_BVALID => gmem_BVALID,
        I_BREADY => ap_const_logic_0,
        I_BRESP => gmem_BRESP,
        I_BID => gmem_BID,
        I_BUSER => gmem_BUSER);

    DMA24b_mm2s_fetch_U0 : component DMA24bUnit_mm2s_DMA24b_mm2s_fetch
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => DMA24b_mm2s_fetch_U0_ap_start,
        start_full_n => start_for_DMA24b_mm2s_streamout_U0_full_n,
        ap_done => DMA24b_mm2s_fetch_U0_ap_done,
        ap_continue => DMA24b_mm2s_fetch_U0_ap_continue,
        ap_idle => DMA24b_mm2s_fetch_U0_ap_idle,
        ap_ready => DMA24b_mm2s_fetch_U0_ap_ready,
        start_out => DMA24b_mm2s_fetch_U0_start_out,
        start_write => DMA24b_mm2s_fetch_U0_start_write,
        m_axi_gmem_AWVALID => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => ap_const_logic_0,
        m_axi_gmem_AWADDR => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => DMA24b_mm2s_fetch_U0_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => DMA24b_mm2s_fetch_U0_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => ap_const_logic_0,
        m_axi_gmem_WDATA => DMA24b_mm2s_fetch_U0_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => DMA24b_mm2s_fetch_U0_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => DMA24b_mm2s_fetch_U0_m_axi_gmem_WLAST,
        m_axi_gmem_WID => DMA24b_mm2s_fetch_U0_m_axi_gmem_WID,
        m_axi_gmem_WUSER => DMA24b_mm2s_fetch_U0_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => DMA24b_mm2s_fetch_U0_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => DMA24b_mm2s_fetch_U0_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => gmem_RLAST,
        m_axi_gmem_RID => gmem_RID,
        m_axi_gmem_RUSER => gmem_RUSER,
        m_axi_gmem_RRESP => gmem_RRESP,
        m_axi_gmem_BVALID => ap_const_logic_0,
        m_axi_gmem_BREADY => DMA24b_mm2s_fetch_U0_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        mm_fifo3_din => DMA24b_mm2s_fetch_U0_mm_fifo3_din,
        mm_fifo3_full_n => mm_fifo_full_n,
        mm_fifo3_write => DMA24b_mm2s_fetch_U0_mm_fifo3_write,
        mm_buffer => image_in);

    DMA24b_mm2s_streamout_U0 : component DMA24bUnit_mm2s_DMA24b_mm2s_streamout
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => DMA24b_mm2s_streamout_U0_ap_start,
        ap_done => DMA24b_mm2s_streamout_U0_ap_done,
        ap_continue => DMA24b_mm2s_streamout_U0_ap_continue,
        ap_idle => DMA24b_mm2s_streamout_U0_ap_idle,
        ap_ready => DMA24b_mm2s_streamout_U0_ap_ready,
        mm_fifo3_dout => mm_fifo_dout,
        mm_fifo3_empty_n => mm_fifo_empty_n,
        mm_fifo3_read => DMA24b_mm2s_streamout_U0_mm_fifo3_read,
        STR_video_out_TDATA => DMA24b_mm2s_streamout_U0_STR_video_out_TDATA,
        STR_video_out_TVALID => DMA24b_mm2s_streamout_U0_STR_video_out_TVALID,
        STR_video_out_TREADY => STR_video_out_TREADY,
        STR_video_out_TKEEP => DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP,
        STR_video_out_TSTRB => DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB,
        STR_video_out_TUSER => DMA24b_mm2s_streamout_U0_STR_video_out_TUSER,
        STR_video_out_TLAST => DMA24b_mm2s_streamout_U0_STR_video_out_TLAST);

    mm_fifo_U : component DMA24bUnit_mm2s_fifo_w128_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => DMA24b_mm2s_fetch_U0_mm_fifo3_din,
        if_full_n => mm_fifo_full_n,
        if_write => DMA24b_mm2s_fetch_U0_mm_fifo3_write,
        if_dout => mm_fifo_dout,
        if_empty_n => mm_fifo_empty_n,
        if_read => DMA24b_mm2s_streamout_U0_mm_fifo3_read);

    start_for_DMA24b_mm2s_streamout_U0_U : component DMA24bUnit_mm2s_start_for_DMA24b_mm2s_streamout_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_DMA24b_mm2s_streamout_U0_din,
        if_full_n => start_for_DMA24b_mm2s_streamout_U0_full_n,
        if_write => DMA24b_mm2s_fetch_U0_start_write,
        if_dout => start_for_DMA24b_mm2s_streamout_U0_dout,
        if_empty_n => start_for_DMA24b_mm2s_streamout_U0_empty_n,
        if_read => DMA24b_mm2s_streamout_U0_ap_ready);




    DMA24b_mm2s_fetch_U0_ap_continue <= ap_const_logic_1;
    DMA24b_mm2s_fetch_U0_ap_start <= ap_start;
    DMA24b_mm2s_streamout_U0_ap_continue <= ap_const_logic_1;
    DMA24b_mm2s_streamout_U0_ap_start <= start_for_DMA24b_mm2s_streamout_U0_empty_n;
    DMA24b_mm2s_streamout_U0_start_full_n <= ap_const_logic_1;
    DMA24b_mm2s_streamout_U0_start_write <= ap_const_logic_0;
    STR_video_out_TDATA <= DMA24b_mm2s_streamout_U0_STR_video_out_TDATA;
    STR_video_out_TKEEP <= DMA24b_mm2s_streamout_U0_STR_video_out_TKEEP;
    STR_video_out_TLAST <= DMA24b_mm2s_streamout_U0_STR_video_out_TLAST;
    STR_video_out_TSTRB <= DMA24b_mm2s_streamout_U0_STR_video_out_TSTRB;
    STR_video_out_TUSER <= DMA24b_mm2s_streamout_U0_STR_video_out_TUSER;
    STR_video_out_TVALID <= DMA24b_mm2s_streamout_U0_STR_video_out_TVALID;
    ap_done <= DMA24b_mm2s_streamout_U0_ap_done;
    ap_idle <= (DMA24b_mm2s_streamout_U0_ap_idle and DMA24b_mm2s_fetch_U0_ap_idle);
    ap_ready <= DMA24b_mm2s_fetch_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= DMA24b_mm2s_streamout_U0_ap_done;
    ap_sync_ready <= DMA24b_mm2s_fetch_U0_ap_ready;
    start_for_DMA24b_mm2s_streamout_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
